worker: 3 # workers are referred to by worker_{id}, master is referred to as master
speed_limit:
  - from_container: master
    to_container: group_1
    limit: 6000

  - from_container: group_1
    to_container: worker_1
    limit: 2000

  - from_container: group_1
    to_container: worker_2
    limit: 4000

  - from_container: master
    to_container: worker_3
    limit: 1000